<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Cadastro de usuários</title>
		<link type="text/css" href="css/default.css" rel="stylesheet" />
		<script type="text/javascript" src="js/jquery.js" ></script>
		<script type="text/javascript" src="js/jquery.validate.js" ></script>
		<script type="text/javascript" src="js/jquery.meio.mask.js" ></script>
		<script type="text/javascript" src="js/default.js" ></script>
	</head>
	<body>
		<div id="mensagem">
			<?php if(isset($mensagem)) echo $mensagem;?>
		</div>
		<div id="cadastro">
			<h2>Cadastro de usuários</h2>
			<form method="post" action="" id="cadastroForm">
				<fieldset>
					<legend title="Cadastro">Cadastro</legend>
					
					<label for="nome">Nome</label>
					<input type="text" name="nome" id="nome" title="nome" class="required" /><br />
					<label for="email">E-mail</label>
					<input type="email" name="email" id="email" title="e-mail" class="required" /><br />
					<label for="host">Host</label>
					<input type="text" name="host" id="host" title="host" class="required" /><br />
					<label for="porta">Porta</label>
					<input type="text" maxlength="5" name="porta" id="porta" title="porta" class="required" /><br />
					<label for="apelido">Apelido</label>
					<input type="text" name="apelido" id="apelido"  title="apelido" class="required" /><br />
					<label for="senha">Senha</label>
					<input type="password" name="senha" id="senha" title="senha" class="required" /><br />
					<input type="submit" value="Cadastrar" id="cadastrar">
				</fieldset>
			</form>
		</div>
	</body>
</html>