<?php
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link type="text/css" href="css/default.css" rel="stylesheet" />
		<script type="text/javascript" src="js/default.js"></script>
		<title>Cadastro de usuário</title>
	</head>
	<body>
		<div id="cadastro">
			<h2>Cadastro realizado com sucesso!</h2>
			<p>
				Verifique em seu e-mail a chave de acesso, para que você tenha acesso ao nosso sistema.
			</p>
			<p>
				<a href="#">Voltar</a>
			</p>
		</div>
	</body>
</html>