<?php
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link type="text/css" href="css/default.css" rel="stylesheet" />
		<script type="text/javascript" src="js/default.js"></script>
		<title>Cadastro de usuário</title>
	</head>
	<body>
		<div id="cadastro">
			<h2>Cadastro de usuários</h2>
			<form method="post" action="#">
				<fieldset>
					<label>Nome</label><br />
					<input type="text" name="nome" id="nome" />
				</fieldset>
				<fieldset>
					<label>E-mail</label><br />
					<input type="text" name="email" id="email" />
				</fieldset>
				<fieldset>
					<label>Host</label><br />
					<input type="text" name="host" id="host" />
				</fieldset>
				<fieldset>
					<label>Porta</label><br />
					<input type="text" name="porta" id="porta" />
				</fieldset>
				<fieldset>
					<label>Apelido</label><br />
					<input type="text" name="apelido" id="apelido" />
				</fieldset>
				<fieldset>
					<label>Senha</label><br />
					<input type="password" name="senha" id="senha" />
				</fieldset>
				<input type="submit" value="Cadastrar" id="cadastrar">
			</form>
		</div>
	</body>
</html>